# [core]
# Specify a non-default location to store blockchain data.
blocksdir=/data/bitcoin.org
# Run in the background as a daemon and accept commands.
daemon=1
# Specify a non-default location to store blockchain and other data.
datadir=/data/bitcoin.org
# Set database cache size in megabytes; machines sync faster with a larger cache. Recommend setting as high as possible based upon machine's available RAM.
dbcache=24000
# Keep the transaction memory pool below <n> megabytes.
maxmempool=1000
# Maintain a full transaction index, used by the getrawtransaction rpc call.
txindex=1

# [rpc]
# Accept command line and JSON-RPC commands.
server=1
# Accept public REST requests.
rest=1
# Listen for JSON-RPC connections on this port
rpcport=8332
